#!/bin/bash
clear
echo "=================================================="
echo " POCKET SOC v3.0 👑 100% OFFLINE MODE"
echo " Built in Ghana GH - Running King Vasco"
echo "=================================================="
echo "1) Start OFFLINE SOC Engine"
echo "2) Stop OFFLINE SOC Engine"
echo "3) View Blocked IPs (REAL)"
echo "4) View Evidence Files (REAL)"
echo "5) Port Scanner (Offline)"
echo "6) Dashboard Stats - localhost:8080"
echo "7) View Blocked IPs"
echo "8) Clear Logs"
echo "9) GeoIP World Map - See attacker locations"
echo "10) Exit"
echo "=================================================="
echo -n "Select option: "
